#!/usr/bin/env ruby

require 'bundler/setup'
require 'discourse_api'
require 'date'
require 'mustache'

today = Date.today

exit if today.cweek.odd? and ENV["ALWAYS_RUN"] != "1"

client = DiscourseApi::Client.new("https://forum.acolab.fr")
client.api_key = File.read('API_KEY').strip
client.api_username = "ACoLaBot"

week_start = today - today.wday + 1
next_meeting = week_start + 7 + 4
date = next_meeting.strftime("%d/%m/%Y")

topic = client.topic(1130)
title = topic["title"]

post_id = topic["post_stream"]["posts"].first["id"]
post = client.get_post(post_id)
text = post["raw"]

title, text = [title, text].map do |string|
  Mustache.render(string, date: date)
end

if ENV["NO_POST"] == "1"
  puts title
  puts "-" * 30
  puts text
  exit
end

client.create_topic(
  category: "FabManagement",
  skip_validations: false,
  auto_track: false,
  title: title,
  raw: text,
  wiki: true,
)
