#!/usr/bin/env ruby

require 'bundler/setup'
require 'discourse_api'
require 'date'
require 'mustache'

today = Date.today

# Régulectif seulement les semaines impaires.
exit if today.cweek.even? and ENV["ALWAYS_RUN"] != "1"

client = DiscourseApi::Client.new("https://forum.acolab.fr")
client.api_key = File.read('API_KEY').strip
client.api_username = "ACoLaBot"

# Détermine le lundi de la semaine en cours
week_start = today - today.wday + 1
next_meeting = week_start + 4 # lundi + 4 = vendredi
date = next_meeting.strftime("%d/%m/%Y")

# https://forum.acolab.fr/t/regulectif-du-date/1130
topic = client.topic(1130)
title = topic["title"]

post_id = topic["post_stream"]["posts"].first["id"]
post = client.get_post(post_id)
text = post["raw"]

title, text = [title, text].map do |string|
  Mustache.render(string, date: date)
end

if ENV["NO_POST"] == "1"
  puts title
  puts "-" * 30
  puts text
  exit
end

client.create_topic(
  category: 18, # FabManagement, voir https://forum.acolab.fr/site.json
  skip_validations: false,
  auto_track: false,
  title: title,
  raw: text,
  wiki: true,
)
